### PR TITLE
Localization Adaptors

### PR DESCRIPTION
**Pull request by alanrtao**
## Description

- Factory 3D printer
- RJ bottle
- Chad race
- Jungle big blob
- Jungle recipe hints
- Player interaction hints
- Skip prompts
- Military unit flag
- Baboon tree
- Magitech gem manager
- Scavenge hunt
- Item name & all collectible names (collectible names stored in locale config CSV instead of scene/prefab CSVs)
- Jungle shape names (stored in locale config)
- Jungle recipe book hints
- Area display name
- Area Discord string

- Made Piratese language with each translation padded with some weird noises :)

## Related Task

- Chad end of game not done AFAIK

## How Has This Been Tested?
Help

### CODE REVIEW

**Comment by alanrtao** [comment]
image
haha pain

**Comment by alanrtao** [comment]
@randomerz how stable is dialogue now? y'all are releasing 2 days later right (or 1)

**Comment by randomerz** [comment]
22 hours until release as of right now

**Comment by alanrtao** [comment]
@randomerz ok first thing congrats for release
and also does off-map fezz do anything?
image

**Comment by randomerz** [comment]
yeah offmap fezziwig is there if you skip village by finishing caves -> doing village. basically it replaces the archeologist + chad npcs in story, but it shouldnt matter for if youre doing village-only demo

**Comment by randomerz** [comment]
omg we released yay

also i was looking at the pixel font is there a reason why we force restart if youre going from not pixel -> pixel, cause i thought it worked before and it was pretty nice that it did

**Comment by alanrtao** [comment]
There was multiple pixel fonts and I don't want to add additional states & parsers for mapping each thing to the right font.
Pixel -> non pixel is fine cuz non pixel is all one font (just that some are bolded, others aren't). Non-pixel -> has always been a force restart / return to main menu type deal.

**Comment by randomerz** [comment]
Oh yeah I think it's fine if one requires menu restart and the other doesn't. esp since I low key think the non-pixel font is a lot nicer lmaooo so I think it would be good if pixel -> non pixel still happened immediately (assuming there's no issues with doing so)

**Comment by randomerz** [comment]
lol https://trello.com/c/AojKs3m3/748-non-pixel-font-is-gigantic

**Pull request closed without merging**
